services:
  exfil:
    image: ghcr.io/scordo/exfil-docker/server:latest
    container_name: exfilserver
    pull_policy: always
    restart: unless-stopped
    network_mode: host
    volumes:
      - data:/home/steam/exfil-dedicated/
    environment:
      - EXFIL_SERVER_NAME=Your cool Server Name
      - EXFIL_MAX_PLAYERS=32
      - EXFIL_SERVER_ROLES=YourSteamID|YourSteamName|Admin

volumes:
  data: