services:
  exfil:
    image: exfil-server
    container_name: exfilserver
    restart: unless-stopped
    network_mode: host
    volumes:
      - data:/home/steam/exfil-dedicated/
    environment:
      - STEAM_USER=YourSteamServerAccountName
      - STEAM_PASSWORD=YourSteamServerAccountPassword

volumes:
  data: