services:
  exfil:
    image: exfil-server
    container_name: exfilserver
    restart: unless-stopped
    network_mode: host
    volumes:
      - data:/home/steam/exfil-dedicated/
    environment:
      - STEAM_USER=YourSteamServerAccountName
      - STEAM_PASSWORD=YourSteamServerAccountPassword
      - EXFIL_SERVER_NAME=Your cool Server Name
      - EXFIL_MAX_PLAYERS=32
      - EXFIL_SERVER_ADMINS=YourSteamID=YourSteamName

volumes:
  data: